### ISSUE TITLE
sha3 install error

### ISSUE THREAD

**Issue by xyths** [Loopring/circulr#166]
when i try to deploy follow this doc https://loopring.github.io/circulr/, i got this when 

`2. cd src/common/loopringjs && npm install 
`

16777 verbose stack Error: sha3@1.2.0 install: `node-gyp rebuild`
16777 verbose stack Exit status 1
16777 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
16777 verbose stack     at EventEmitter.emit (events.js:182:13)
16777 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
16777 verbose stack     at ChildProcess.emit (events.js:182:13)
16777 verbose stack     at maybeClose (internal/child_process.js:961:16)
16777 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
16778 verbose pkgid sha3@1.2.0
16779 verbose cwd /Users/$USERNAME/work/code/circulr/src/common/loopringjs
16780 verbose Darwin 17.6.0
16781 verbose argv "/usr/local/Cellar/node/10.5.0_1/bin/node" "/usr/local/bin/npm" "install"
16782 verbose node v10.5.0
16783 verbose npm  v6.1.0
16784 error code ELIFECYCLE
16785 error errno 1
16786 error sha3@1.2.0 install: `node-gyp rebuild`
16786 error Exit status 1
16787 error Failed at the sha3@1.2.0 install script.
16787 error This is probably not a problem with npm. There is likely additional logging output above.
16788 verbose exit [ 1, true ]

anyone knows what's wrong with it?

**Comment by xyths** [comment]
when i try
`$ npm install sha3`
almost same error

**Comment by xyths** [comment]
upgrade node from 10.5.0 to 10.6.0, fix.
